branches:
  # all branches
  only:
  - gh-pages
  - /.*/

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - docker

before_install:
  - sudo apt-get install libgnutls28-dev

install:
  # Build/test dependencies
  - pip install --upgrade pip
  - pip install --no-cache-dir -r requirements/30_preprocess_web.txt
  - pip install coveralls

script:
  # Run django tests.  (Note django settings are an env variable)
  - cd preprocess; python -m unittest; cd ..
  - cd preprocess_web/code; python manage.py test; cd ../../
  #- coverage run --source=ravens_metadata_apps.ta2_interfaces manage.py test ravens_metadata_apps.ta2_interfaces ravens_metadata_apps.workspaces
  #- docker build -t tworavens/ravens-main:latest .
  - echo $TRAVIS_BRANCH;

after_success:
  # Build an image and push to dockerhub
  - echo $TRAVIS_BRANCH;
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
    docker build -t tworavens/raven-metadata-service:latest -f ./Dockerfile-web .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push tworavens/raven-metadata-service:latest;
    fi
  - if [ "$TRAVIS_BRANCH" = "xdevelop" ]; then
    docker build -t tworavens/raven-metadata-service:develop -f ./Dockerfile-web .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push tworavens/raven-metadata-service:develop;
    fi
# send report to coveralls
#after_success:
# coveralls
