FROM python:3.6.4
MAINTAINER TwoRavens http://2ra.vn/

LABEL organization="Two Ravens" \
      2ra.vn.version="0.0.4-alpha" \
      2ra.vn.release-date="2018-06-15" \
      description="Web service for preprocessing tabular data"

# -------------------------------------
# Install debugging tools
# -------------------------------------
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    apt-utils\
    iputils-ping \
    telnet \
    vim

# -------------------------------------
# Set the workdir
# -------------------------------------
WORKDIR /var/webapps/raven-metadata-service

# -------------------------------------
# Copy over the requirements and run them
# -------------------------------------
COPY ./requirements/ ./requirements
RUN pip3 install --no-cache-dir -r requirements/30_preprocess_web.txt

# -------------------------------------
# Create a volume for sharing between containers
# -------------------------------------
VOLUME /raven_metadata

# -------------------------------------
# Expose port for web communication
# - web: 8080
# -------------------------------------
EXPOSE 8080

# -------------------------------------
# Set env variables
# -------------------------------------
ENV DJANGO_SETTINGS_MODULE=ravens_metadata.settings.local_settings

# -------------------------------------
# Install R base
# -------------------------------------
#RUN apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'
#RUN apt-get install -y software-properties-common
#RUN add-apt-repository 'deb https://cloud.r-project.org/bin/linux/debian stretch-cran35/'

#RUN printf "deb http://cran.rstudio.com/bin/linux/debian jessie-cran35/" > /etc/apt/sources.list

RUN apt-get install -y r-base
RUN R -e 'install.packages("rjson", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("DescTools", repos="http://cran.rstudio.org")' && \
    R -e 'install.packages("XML", repos="http://cran.rstudio.org")'
ENV R_SCRIPT_PATH=/usr/bin/Rscript

# -------------------------------------
# Copy over the rest of the repository
# -------------------------------------
COPY . .

# -------------------------------------
# Copy the metadata web server start command +
#   preprocess script
# -------------------------------------
COPY startup_scripts/metadata_start.sh /usr/bin/metadata_start.sh
COPY preprocess/scripts/preprocess_file.sh /usr/bin/preprocess_file.sh
RUN chmod u+x /usr/bin/metadata_start.sh && \
    chmod u+x /usr/bin/preprocess_file.sh


# -------------------------------------
# Update the working directory
# -------------------------------------
WORKDIR /var/webapps/raven-metadata-service/preprocess_web/code

# -------------------------------------
# Run preprocess against the entry point input param
# -------------------------------------
#ENTRYPOINT ["/usr/bin/preprocess_file.sh"]

CMD echo 'Starting preprocess web server.' && \
    fab init_db && \
    python manage.py runserver 0.0.0.0:8080

#RUN cd preprocess  && \
#    python preprocess.py
