# -------------------------------
# Rudimentary docker-compose for local testing
# "docker-compose up" should run a web service at:
#   http://0.0.0.0:8080/
# -------------------------------

version: '3'
services:
  # -------------------------------
  # Redis
  # -------------------------------
  redis:
    image: redis:4.0
    hostname: redis
    volumes:
      - app-volume:/tmp
    ports:
      - '6379:6379'
  # -------------------------------
  # Django web server
  # -------------------------------
  web:
    image: tworavens/raven-metadata-service
    hostname: web
    environment:
      - DJANGO_DEBUG=true
      - DJANGO_SETTINGS_MODULE=ravens_metadata.settings.docker_test_settings
      - REDIS_HOST=redis
      - PREPROCESS_DATA_DIR=/raven_metadata
      - EDITOR_URL=

    #command: python manage.py runserver 8080
    volumes:
      - app-volume:/tmp
      - preprocess-volume:/raven_metadata
    ports:
      - "8080:8080"
    # set up links so that web knows about db, rabbit and redis
    links:
      - celery_queue
      - redis
    depends_on:
      - celery_queue
  # -------------------------------
  # Celery worker
  # -------------------------------
  celery_queue:
    image: tworavens/raven-metadata-service
    command: celery -A ravens_metadata worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=ravens_metadata.settings.docker_test_settings
      - REDIS_HOST=redis
      - PREPROCESS_DATA_DIR=/raven_metadata
    volumes:
      - app-volume:/tmp
      - preprocess-volume:/raven_metadata
    links:
      - redis
    depends_on:
      - redis
volumes:
  app-volume:
  preprocess-volume:
