# Generated by Django 2.2 on 2019-11-05 14:43

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('schema_type', models.CharField(default='PREPROCESS_CORE_METADATA', max_length=255)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('schema_json', jsonfield.fields.JSONField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
