# Generated by Django 2.0.3 on 2018-06-11 14:13

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('schema_type', models.CharField(default='PREPROCESS_CORE_METADATA', max_length=255)),
                ('version', models.DecimalField(decimal_places=2, max_digits=8, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_latest', models.BooleanField(default=True)),
                ('schema_file', models.FileField(upload_to='source_file/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
