# Generated by Django 2.0.3 on 2018-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataschema',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='schema_file',
            field=models.FileField(upload_to='schema_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='version',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
