# Generated by Django 2.0.3 on 2018-06-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_schemas', '0002_auto_20180611_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataschema',
            name='name',
            field=models.CharField(max_length=555, unique=True),
        ),
    ]
