# Generated by Django 2.0.3 on 2018-06-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_schemas', '0003_auto_20180611_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadataschema',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
