# Generated by Django 2.0.3 on 2018-06-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_schemas', '0004_auto_20180612_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataschema',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
