apiVersion: v1
kind: Service
metadata:
  name: ravens-preprocess-svc
  labels:
    app: tworavens-preprocess-app
spec:
  selector:
    app: tworavens-preprocess-app
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
