---
apiVersion: v1
kind: Service
metadata:
  name: ravens-preprocess-svc
  labels:
    app: ravens-preprocess-svc
spec:
  selector:
    app: tworavens-preprocess-app
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  # metadata.2ravens.org
  loadBalancerIP: 35.192.35.125
---
# ---------------------------------------------------------
# EventData - Kubernetes Pod File
# ---------------------------------------------------------
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tworavens-preprocess-app
  labels:
    app: tworavens-preprocess-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tworavens-preprocess-app
        tier: web
    spec:
      restartPolicy: Always
      volumes:
        - name: raven-metadata-volume
          emptyDir: {}
      containers:
      # -------------------------
      # 1 of 3: redis
      # -------------------------
      - name: redis
        image: redis:4.0
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        ports:
        - containerPort: 6379
      # -------------------------
      # 2 of 3: celery worker
      # -------------------------
      - name: celery-worker
        image: tworavens/raven-metadata-service:latest
        #imagePullPolicy: IfNotPresent
        command: ['celery', '-A', 'ravens_metadata', 'worker', '-l', 'info']
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: "ravens_metadata.settings.gce_deploy_settings"
          - name: REDIS_HOST
            # Note this is within the same pod
            value: localhost
        volumeMounts:
          - name: "raven-metadata-volume"
            mountPath: "/raven_metadata"
            readOnly: false
            #valueFrom:
            #  secretKeyRef:
            #    name: postgres-credentials
            #    key: user
      # -------------------------
      # 3 of 3: web server
      # -------------------------
      - name: preprocess-web
        image: tworavens/raven-metadata-service:latest
        #imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: "ravens_metadata.settings.gce_deploy_settings"
          - name: REDIS_HOST
            # Note this is within the same pod
            value: localhost
          - name: DJANGO_DEBUG
            value: "True"
          - name: SWAGGER_HOST
            value: "metadata.2ravens.org"
          - name: EDITOR_URL
            value:
          - name: GCE_CREDS_INFO
            valueFrom:
              secretKeyRef:
                name: gce-creds-variable
                key: GCE_CREDS_INFO
        volumeMounts:
          - name: "raven-metadata-volume"
            mountPath: "/raven_metadata"
            readOnly: false
        # liveness is for restart
        livenessProbe:
          httpGet:
            path: /monitoring/alive
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        # readiness: ready for traffic
        readinessProbe:
          httpGet:
            path: /monitoring/alive
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
