---
apiVersion: v1
kind: Service
metadata:
  name: ravens-preprocess-svc
  labels:
    app: ravens-preprocess-svc
spec:
  selector:
    app: ravens-preprocess-app
    tier: web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  # This IP is tied to: metadata.2ravens.org
  loadBalancerIP: 35.192.35.125
---
# ---------------------------------------------------------
# EventData - Kubernetes Pod File
# ---------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: ravens-preprocess-app
  labels:
    app: ravens-preprocess-app
    tier: web
spec:
  restartPolicy: Always
  volumes:
    - name: raven-metadata-volume
      emptyDir: {}
    - name: cloudsql-instance-credentials
      secret:
        secretName: cloudsql-instance-credentials
  containers:
  # --------------------------------
  # 1 of 5: Ravens nginx
  # - reverse proxy for psi-main
  # --------------------------------
  - name: metadata-nginx
    image: tworavens/raven-metadata-nginx:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    volumeMounts:
    - name: "raven-metadata-volume"
      mountPath: "/raven_metadata"
      readOnly: true
  # -------------------------
  # 2 of 5: redis
  # -------------------------
  - name: redis
    image: redis:4.0
    #resources:
    #  requests:
    #    cpu: 100m
    #    memory: 100Mi
    ports:
    - containerPort: 6379
  # -------------------------
  # 3 of 5: cloudsql proxy
  # -------------------------
  - name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: ["/cloud_sql_proxy",
              "-instances=raven2-186120:us-central1:raven-mysql-metadata-svc=tcp:3306",
              "-credential_file=/secrets/cloudsql/credentials.json"]
    volumeMounts:
    - name: cloudsql-instance-credentials
      mountPath: /secrets/cloudsql
      readOnly: true
  # -------------------------
  # 4 of 5: celery worker
  # -------------------------
  - name: celery-worker
    image: tworavens/raven-metadata-service:latest
    imagePullPolicy: Always
    command: ['celery', '-A', 'ravens_metadata', 'worker', '-l', 'info']
    envFrom:
    - configMapRef:
        name: metadata-python-configmap
    env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: metadata-web-secrets
          key: SECRET_KEY
    - name: GCE_CREDS_INFO
      valueFrom:
        secretKeyRef:
          name: gce-creds-variable
          key: GCE_CREDS_INFO
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: cloudsql-db-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cloudsql-db-credentials
          key: password
    volumeMounts:
      - name: "raven-metadata-volume"
        mountPath: "/raven_metadata"
        readOnly: false
        #valueFrom:
        #  secretKeyRef:
        #    name: postgres-credentials
        #    key: user
  # -------------------------
  # 5 of 5: web server
  # -------------------------
  - name: preprocess-web
    image: tworavens/raven-metadata-service:latest
    imagePullPolicy: Always
    command: ["metadata_start.sh"]
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    envFrom:
    - configMapRef:
        name: metadata-python-configmap
    env:
    - name: GCE_CREDS_INFO
      valueFrom:
        secretKeyRef:
          name: gce-creds-variable
          key: GCE_CREDS_INFO
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: cloudsql-db-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cloudsql-db-credentials
          key: password
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: metadata-web-secrets
          key: SECRET_KEY
    volumeMounts:
    - name: "raven-metadata-volume"
      mountPath: "/raven_metadata"
      readOnly: false
    # liveness is for restart
    livenessProbe:
      httpGet:
        path: /monitoring/alive
        port: 8080
      initialDelaySeconds: 30
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    # readiness: ready for traffic
    readinessProbe:
      httpGet:
        path: /monitoring/alive
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
