apiVersion: v1
kind: Service
metadata:
  name: ravens-preprocess-svc
  labels:
    app: tworavens-preprocess-app
spec:
  selector:
    app: tworavens-preprocess-app
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  # metadata.2ravens.org
  loadBalancerIP: 35.192.35.125
  #
  # 2ravens.org
  #loadBalancerIP: 104.197.235.238
