# Generated by Django 2.0.3 on 2018-03-19 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raven_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 15, 58, 10, 398861)),
            preserve_default=False,
        ),
    ]
