# Generated by Django 2.0.3 on 2018-03-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raven_auth', '0002_user_token_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token_created',
            new_name='token_updated',
        ),
    ]
