# Generated by Django 2.0.3 on 2018-03-08 01:17

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('PENDING', 'PENDING'), ('DATA_RETRIEVED', 'DATA_RETRIEVED'), ('PREPROCESS_STARTED', 'PREPROCESS_STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED')], default='RECEIVED', max_length=100)),
                ('user_message', models.TextField(blank=True, help_text='May be used for error messages, etc')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='queue task id (e.g. celery id)')),
                ('source_file_url', models.URLField(blank=True, verbose_name='direct download url (optional)')),
                ('source_file', models.FileField(blank=True, upload_to='source_file/%Y/%m/%d/', verbose_name='pointer to source file (deleted after processed)')),
                ('preprocess_file', models.FileField(blank=True, upload_to='preprocess_file/%Y/%m/%d/', verbose_name='pointer to summary metadata')),
                ('schema_version', models.CharField(max_length=100)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
