# Generated by Django 2.0.3 on 2018-04-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadataupdate',
            unique_together={('orig_metadata', 'version_number')},
        ),
    ]
