# Generated by Django 2.0.3 on 2018-05-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessjob',
            name='source_file',
            field=models.FileField(blank=True, help_text='Source file to analyze', upload_to='source_file/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='preprocessjob',
            name='state',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('PENDING', 'PENDING'), ('STATE_RETRIEVING_DATA', 'STATE_RETRIEVING_DATA'), ('DATA_RETRIEVED', 'DATA_RETRIEVED'), ('PREPROCESS_STARTED', 'PREPROCESS_STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='RECEIVED', max_length=100),
        ),
    ]
