# Generated by Django 2.2 on 2019-05-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess_jobs', '0002_auto_20180502_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprocessjob',
            options={'ordering': ('-created',), 'permissions': (('view_preprocess_job', 'View Preprocess Job'),)},
        ),
    ]
