# Generated by Django 2.0.3 on 2018-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess_jobs', '0002_auto_20180308_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessjob',
            name='is_metadata_public',
            field=models.BooleanField(default=True),
        ),
    ]
