# Generated by Django 2.0.3 on 2018-04-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess_jobs', '0003_auto_20180405_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessjob',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
