# Generated by Django 2.0.3 on 2018-03-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess_jobs', '0003_preprocessjob_is_metadata_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprocessjob',
            options={'permissions': (('view_preprocess_job', 'View Preprocess Job'),)},
        ),
    ]
