# Generated by Django 2.0.3 on 2018-03-19 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preprocess_jobs', '0004_auto_20180319_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessjob',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
