# Generated by Django 2.0.3 on 2018-03-30 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preprocess_jobs', '0005_preprocessjob_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('update_json', jsonfield.fields.JSONField()),
                ('metadata_file', models.FileField(blank=True, help_text='Summary metadata created by preprocess', upload_to='preprocess_file/%Y/%m/%d/')),
                ('note', models.TextField(blank=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orig_metadata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orig_metadata', to='preprocess_jobs.PreprocessJob')),
                ('previous_metadata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previous_metadata', to='preprocess_jobs.PreprocessJob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
