# Generated by Django 2.0.3 on 2018-04-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess_jobs', '0006_metadataupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadataupdate',
            options={'ordering': ('-created',)},
        ),
    ]
