# Generated by Django 2.0.3 on 2018-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse_connect', '0003_auto_20180501_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataversefileinfo',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='original filename'),
        ),
    ]
