# Generated by Django 2.0.3 on 2018-05-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse_connect', '0004_dataversefileinfo_original_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataversefileinfo',
            old_name='dataverse_doi',
            new_name='dataset_doi',
        ),
    ]
