# Generated by Django 2.0.3 on 2018-07-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataverse_connect', '0008_auto_20180713_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataversefileinfo',
            name='persistent_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='persistentId'),
        ),
    ]
